# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    docker build -t frontend-syllabus:latest .
    docker run frontend-syllabus:latest run prettier:check
    docker run frontend-syllabus:latest run test:classes-and-objects
  displayName: 'Build'
